[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "DUBSlib"
version = "0.1.0"
description = "My collection of useful classes, functions, and constants."

readme = "README.md"

authors = [
    { name = "Donald Raymond Reilly Jr.", email = "donald.reilly.jr@outlook.com" }
]
[tool.setuptools.packages.find]
where = ["src"]
