[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "dubslib"
version = "0.1.0"
description = "A collection of functions and constant variables."

readme = "README.md"

authors = [
    { name = "Donald Raymond Reilly Jr.", email = "donald.reilly.jr@outlook.com" }
]
[tool.setuptools.packages.find]
where = ["src"]
